version: '3.7'

services:
  api:
    build:
      context: ./src
      dockerfile: ../Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - docker-compose.env
    volumes:
      - ./src:/app/

  db:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    env_file:
      - docker-compose.env
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:6.20
    restart: always
    env_file:
      - docker-compose.env
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  db-data:
  pgadmin-data: